### ISSUE TITLE
Cell Segmentaion

### ISSUE THREAD

**Issue by rocketeer1998** [Moldia/HybrISS#2]
Hello @sergiomarco25 , thanks for your great work! I'd like to know how to do cell segmentation and to get the gene expression matrix using Python, CellProfiler, or R?

**Comment by sergiomarco25** [comment]
Hi, We typically use either cellpose (https://www.cellpose.org/), Ilastik or the commercial software BIAS (not available for now). For Elastik and bias we used the GUI of these models. For cellpose you could find some of the scripts you are asking for within the ISS_postprocessing repository ([in MolDia](https://github.com/Moldia)).

**Comment by rocketeer1998** [comment]
Thanks a lot!
